- name: Install packages
  ansible.builtin.apt:
    name:
      - "cyrus-imapd"
  notify: Restart Cyrus IMAP

- name: Configure SSL
  ansible.builtin.include_tasks: "configure-ssl.yml"

- name: Generate Cyrus IMAP services file cyrus.conf
  vars:
    services: "{{ cyrus_imap_default_services | ansible.builtin.combine(cyrus_imap_services, recursive=true) }}"
  ansible.builtin.template:
    src: "templates/cyrus.conf"
    dest: "/etc/cyrus.conf"
    mode: "0644"
  notify: Restart Cyrus IMAP

- name: Generate Cyrus IMAP configuration file imapd.conf
  vars:
    config: "{{ cyrus_imap_default_config | ansible.builtin.combine(cyrus_imap_config) }}"
  ansible.builtin.template:
    src: "templates/imapd.conf"
    dest: "/etc/imapd.conf"
    mode: "0644"
  notify: Restart Cyrus IMAP
